---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


# Build on top of a common base
bases:
  - ../base/
## If there's custom resources, add them here, otherwise
##  only customize on top of base
#resources:
#  - another-k8s.yaml

patchesStrategicMerge:
  - overlay.yml