---
apiVersion: apps/v1
kind: Deployment

## This deployment must use a different name (a new ReplicaSet)
##   but still use all the same selectors.
## But Kustomize merges an overlay via the name, so we can't use Kustomize.
metadata:
  name: cartapp-foo
spec:
  template:
    spec:
      containers:
      - name: cartapp
        image: ignasi35/shopping-cart-service-scala:latest
        env:
          - name: JAVA_OPTS
            value: "-Dconfig.resource=kubernetes.conf -Dakka.cluster.roles.0=foo"